# This rule is not used by the project data-gravity-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the hep.hep.cern.local.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: data-gravity-operator
    app.kubernetes.io/managed-by: kustomize
  name: physicsjob-editor-role
rules:
- apiGroups:
  - hep.hep.cern.local
  resources:
  - physicsjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hep.hep.cern.local
  resources:
  - physicsjobs/status
  verbs:
  - get
